//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTIER.EFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_history
    {
        public int BusinessEntityID { get; set; }
        public string PersonType { get; set; }
        public string NameStyle { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public int EmailPromotion { get; set; }
        public string AdditionalContactInfo { get; set; }
        public string Demographics { get; set; }
        public string rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.DateTime log_tarih { get; set; }
    }
}
